### PR TITLE
Fixes #86 and #106 - properly handle token expiry in the sabre dav au…

### LINKED ISSUE #86: Exception: OpenID Connect token expired leads to 500
Set up owncloud and follow the ocis bridge (install graphapi and openidconnect apps, run ocis-glauth & ocis-konnectd) to get oc10 authenticated against konnectd with the accounts existing in owncloud

initial login works, but as soon as the token expires the android apps do not refresh the token.

I used openidconnect master as well as oauth2 master and see this log line:

```
{
    "reqId":"07547f8c-1fa9-4164-b798-e4f39c35e188",
    "level":4,
    "time":"2020-06-21T21:45:22+00:00",
    "remoteAddr":"172.19.0.2",
    "user":"jfd",
    "app":"webdav",
    "method":"PROPFIND",
    "url":"\/remote.php\/dav\/files\/jfd\/...\/",
    "message":"Exception: OpenID Connect token expired: {
        \"Exception\":\"OC\User\LoginException\",
        \"Message\":\"OpenID Connect token expired\",
        \"Code\":0,
        \"Trace\": \"
            #0 /apps/openidconnect/lib/Sabre/OpenIdSabreAuthBackend.php(115): OCA\OpenIdConnect\OpenIdConnectAuthModule->authToken('eyJhbGciOiJQUzI...')
            #1 /lib/composer/sabre/dav/lib/DAV/Auth/Backend/AbstractBearer.php(96): OCA\OpenIdConnect\Sabre\OpenIdSabreAuthBackend->validateBearerToken('eyJhbGciOiJQUzI...')
            #2 /lib/composer/sabre/dav/lib/DAV/Auth/Plugin.php(182): Sabre\DAV\Auth\Backend\AbstractBearer->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
            #3 /lib/composer/sabre/dav/lib/DAV/Auth/Plugin.php(137): Sabre\DAV\Auth\Plugin->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
            #4 /lib/composer/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
            #5 /lib/composer/sabre/dav/lib/DAV/Server.php(454): Sabre\DAV\Server->emit('beforeMethod:PR...', Array)
            #6 /lib/composer/sabre/dav/lib/DAV/Server.php(251): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
            #7 /apps/dav/lib/Server.php(329): Sabre\DAV\Server->start()
            #8 /apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
            #9 /remote.php(165): require_once('/var/www/ownclo...')
        #10 {main}\",
        \"File\":\"/apps/openidconnect/lib/OpenIdConnectAuthModule.php\",
        \"Line\":107
    }
"}
```

this leads to a 500 in apache
```
owncloud-apache    | 172.19.0.2 - - [21/Jun/2020:21:56:51 +0000] "PROPFIND /remote.php/dav/files/jfd/.../ HTTP/1.1" 500 214
```

android log:
```
D/(CheckPathExistenceRemoteOperation.kt:84) .run(): Existence check for https://.../remote.php/dav/files/jfd/.../ finished with HTTP status 500(FAIL)
E/(UploadFileOperation.java:378) .run(): Upload of /storage/emulated/0/owncloud/tmp/jfd@.../DSC_0064.JPG to .../DSC_0064.JPG: The ownCloud server is not configured!
D/(UploadsStorageManager.java:472) .updateDatabaseUploadResult(): updateDataseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@213bdc2 upload: com.owncloud.android.operations.ChunkedUploadFileOperation@c4517d3
V/(UploadsStorageManager.java:173) .updateUploadInternal(): Updating /storage/emulated/0/owncloud/tmp/jfd@.../DSC_0064.JPG with status:UPLOAD_FAILED and result:UNKNOWN (old:/storage/emulated/0/owncloud/tmp/jfd@.../DSC_0064.JPG status:UPLOAD_IN_PROGRESS result:-1)
```

Refreshing the authentication in the android app by going to the accounts and clicking on the key icon does not seem to update the token that is used for the uploads ... retrying uploads still fails ... could it be that the token does not change? hm the new upload requests at least start withk the same token `eyJhbGciOiJQUzI..` in the log...

well and a 500 does not tell the client to reauthenticate ...

Related:
- https://github.com/owncloud/oauth2/issues/255
- https://github.com/owncloud/core/issues/37059
- https://github.com/owncloud/core/pull/37043 (same error)

### LINKED ISSUE #106: [QA] [OIDC] Token refresh fails
Tested with server 10.5 + openidconnect 1.0.0RC4 for owncloud/openidconnect#66 + desktop client testpilotcloud version 2.7.0daily20201004 (build 2209)

* connect via oidc
* wait a few minutes
* add a local folder, upload starts
* wait for an explosion:
image

Despite the above error, the upload went fine:
image

Expected behaviour: The client does a refresh automatically, when the token expires.
Workaround: Client -> Account -> log out / log in fixes the situation. But requires a confirmation on the IDP page. 

Client log:
[20201008_0929_owncloud.log.0.zip](https://github.com/owncloud/client/files/5346118/20201008_0929_owncloud.log.0.zip)

server log:
[jw-openidconnect-1-0-0rc4-test-vbw0q.log.zip](https://github.com/owncloud/client/files/5346141/jw-openidconnect-1-0-0rc4-test-vbw0q.log.zip)

@TheOneRing Please transfer to owncloud/openidconnect, if you think this is more a server bug.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…th backend for openidconnect

## Description
token expiry shall not lead to 500 but a proper 401

## Related Issue
- Fixes #86 
- Fixes #106 

## How Has This Been Tested?
- :hand: 
- unit tests added

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

File: lib/Sabre/OpenIdSabreAuthBackend.php [hunk 1]
```diff
@@ -110,18 +110,23 @@ private function isDavAuthenticated($username) {
...
+					return false;
+				}
+
+				// setup the user
+				$userId = $this->userSession->getUser()->getUID();
+				$this->setupFilesystem($userId);
+				$this->session->close();
+				return $this->principalPrefix . $userId;
+			} catch (\Exception $ex) {
+				$this->session->close();
```
Comment (jnweiger) [inline lib/Sabre/OpenIdSabreAuthBackend.php:127]: I would expect code that checks for expired token and then do some actions to refresh it. 
I don't understand what is going on here. some comments would be helpful.
I have an easy reproducer to test the 10min timeout, so whatever it does, I can easily veryfy, if it is successful afterwards :-)

**Review by jnweiger — APPROVED** [review]
I would expect code that checks for expired token and then do some actions to refresh it.
I don't understand what is going on here. some comments would be helpful.
I have an easy reproducer to test the 10min timeout, so whatever it does, I can easily veryfy, if it is successful afterwards :-)

File: lib/Sabre/OpenIdSabreAuthBackend.php (hunk 1 above)
Comment (DeepDiver1975) [reply lib/Sabre/OpenIdSabreAuthBackend.php:127]: > I would expect code that checks for expired token and then do some actions to refresh it.

We as the reply party cannot refresh the token - this is upon the clients to take care.
(The server has no refresh token)

**Review by micbar — APPROVED** [review]
